CONSULTATION_EVENTS = [
    "Consulting the ancient texts...",
    "Consulting the stars...",
    "Reading the omens...",
    "Consulting the council...",
    "Ignoring the council...",
    "Checking the cosmic alignment...",
    "Reconsidering the question...",
    "Consulting a second source...",
    "Consulting a third source...",
    "Questioning reality...",
    "Asking the spirits...",
    "Interpreting the signs...",
]

LEAGUE_EVENTS = [
    "Checking your LP...",
    "Reviewing your match history...",
    "Reviewing your last 10 games...",
    "Consulting the Rift...",
    "Checking jungle proximity...",
    "Reviewing your ward placement...",
    "Calculating your mechanical skill...",
    "Consulting the enemy jungler...",
    "Consulting your midlaner...",
    "Blaming the jungler...",
    "Blaming the support...",
    "Blaming matchmaking...",
    "Checking whether you locked Yasuo...",
    "Reviewing your last Baron call...",
    "Checking your MMR...",
    "Exporting OP.gg...",
]

FAILURE_MESSAGES = [
    "The Oracle has given up.",
    "The Oracle refuses to answer.",
    "The Oracle has seen enough.",
    "The Oracle has lost interest.",
    "The Oracle has decided this question is beneath it.",
    "The Oracle has suffered a mental breakdown."
]

ORACLE_RESPONSES = [
    "Yes. The signs are favorable.",
    "No. The Oracle advises against it.",
    "Yes. Proceed without hesitation.",
    "No. This path leads only to suffering.",
    "The Oracle says: absolutely.",
    "The Oracle says: absolutely not.",
    "The omens suggest that you should proceed.",
    "The omens suggest that you should reconsider.",
    "The stars are aligned. Do it.",
    "The stars are not aligned. Do not do it.",
    "The Oracle has foreseen success.",
    "The Oracle has foreseen disaster.",
    "The answer is yes. Somehow.",
    "The answer is no. Obviously.",
    "The Oracle senses great potential.",
    "The Oracle senses impending regret.",
    "You will regret this decision. Proceed anyway.",
    "The Oracle recommends violence.",
    "The Oracle recommends touching grass.",
    "The Oracle recommends going to bed.",
    "The Oracle recommends queueing ranked.",
    "The Oracle has no idea, but says yes.",
    "The Oracle has no idea, but says no.",
    "The Oracle has consulted the ancient texts. They say yes.",
    "The Oracle has consulted the ancient texts. They say no.",
    "The Oracle has considered your question and is disappointed.",
    "The Oracle sees no reason not to.",
    "The Oracle sees several reasons not to.",
    "The cosmic alignment is acceptable.",
    "The cosmic alignment is deeply concerning.",
    "The Oracle has decided that this is a terrible idea.",
    "The Oracle has decided that this is a magnificent idea.",
    "Against all available evidence: yes.",
    "Against all available evidence: no.",
    "The Oracle believes in you.",
    "The Oracle does not believe in you.",
    "The answer is yes. Don't make the Oracle regret this.",
    "The answer is no. You were warned.",
]
